use super::item_type::ItemType;

pub fn item_tex_layer(item: &ItemType) -> f32 {
    match item {
        ItemType::Block(b) => b.tex_layer(),
        ItemType::Apple => 8.0,
        ItemType::Bread => 9.0,
        ItemType::Bucket => 10.0,
        ItemType::WaterBucket => 11.0,
        ItemType::DiamondSword => 12.0,
        ItemType::DiamondPickaxe => 13.0,
        ItemType::WhiteWool => 34.0,
        ItemType::Coal => 39.0,
        ItemType::Stick => 40.0,
        ItemType::IronIngot => 41.0,
        ItemType::Porkchop => 42.0,
        ItemType::CookedPorkchop => 43.0,
        ItemType::Beef => 44.0,
        ItemType::CookedBeef => 45.0,
        ItemType::Mutton => 46.0,
        ItemType::CookedMutton => 47.0,
        ItemType::Leather => 48.0,
        ItemType::WoodenPickaxe => 49.0,
        ItemType::StonePickaxe => 50.0,
        ItemType::IronPickaxe => 51.0,
        ItemType::WoodenSword => 52.0,
        ItemType::StoneSword => 53.0,
        ItemType::IronSword => 54.0,
        ItemType::Diamond => 55.0,
        ItemType::WoodenAxe => 56.0,
        ItemType::StoneAxe => 57.0,
        ItemType::IronAxe => 58.0,
        ItemType::DiamondAxe => 59.0,
        ItemType::WoodenShovel => 60.0,
        ItemType::StoneShovel => 61.0,
        ItemType::IronShovel => 62.0,
        ItemType::DiamondShovel => 63.0,
        ItemType::WoodenHoe => 64.0,
        ItemType::StoneHoe => 65.0,
        ItemType::IronHoe => 66.0,
        ItemType::DiamondHoe => 67.0,
    }
}
