use super::item_type::ItemType;

pub fn item_tex_layer(item: &ItemType) -> f32 {
    match item {
        ItemType::Block(b) => b.tex_layer(),
        ItemType::Apple => 8.0,
        ItemType::Bread => 9.0,
        ItemType::Bucket => 10.0,
        ItemType::WaterBucket => 11.0,
        ItemType::DiamondSword => 12.0,
        ItemType::DiamondPickaxe => 13.0,
        ItemType::WhiteWool => 34.0,
        ItemType::Coal => 36.0,
        ItemType::Stick => 37.0,
        ItemType::IronIngot => 38.0,
        ItemType::Porkchop => 39.0,
        ItemType::CookedPorkchop => 40.0,
        ItemType::Beef => 41.0,
        ItemType::CookedBeef => 42.0,
        ItemType::Mutton => 43.0,
        ItemType::CookedMutton => 44.0,
        ItemType::Leather => 45.0,
        ItemType::WoodenPickaxe => 46.0,
        ItemType::StonePickaxe => 47.0,
        ItemType::IronPickaxe => 48.0,
        ItemType::WoodenSword => 49.0,
        ItemType::StoneSword => 50.0,
        ItemType::IronSword => 51.0,
        ItemType::Diamond => 52.0,
        ItemType::WoodenAxe => 53.0,
        ItemType::StoneAxe => 54.0,
        ItemType::IronAxe => 55.0,
        ItemType::DiamondAxe => 56.0,
        ItemType::WoodenShovel => 57.0,
        ItemType::StoneShovel => 58.0,
        ItemType::IronShovel => 59.0,
        ItemType::DiamondShovel => 60.0,
        ItemType::WoodenHoe => 61.0,
        ItemType::StoneHoe => 62.0,
        ItemType::IronHoe => 63.0,
        ItemType::DiamondHoe => 64.0,
    }
}
