use super::ItemType;
use crate::world::block::BlockType;

pub fn item_to_u8(it: &ItemType) -> u8 {
    match it {
        ItemType::Block(BlockType::Grass) => 0,
        ItemType::Block(BlockType::Dirt) => 1,
        ItemType::Block(BlockType::Wood) => 2,
        ItemType::Block(BlockType::Stone) => 3,
        ItemType::Apple => 4,
        ItemType::Bread => 5,
        ItemType::Bucket => 6,
        ItemType::WaterBucket => 7,
        ItemType::DiamondSword => 8,
        ItemType::DiamondPickaxe => 9,
        ItemType::Porkchop => 10,
        ItemType::CookedPorkchop => 11,
        ItemType::Beef => 12,
        ItemType::CookedBeef => 13,
        ItemType::Mutton => 14,
        ItemType::CookedMutton => 15,
        ItemType::WhiteWool => 16,
        ItemType::Leather => 17,
        ItemType::Stick => 18,
        ItemType::Coal => 19,
        ItemType::IronIngot => 20,
        ItemType::WoodenPickaxe => 21,
        ItemType::StonePickaxe => 22,
        ItemType::IronPickaxe => 23,
        ItemType::WoodenSword => 24,
        ItemType::StoneSword => 25,
        ItemType::IronSword => 26,
        ItemType::Diamond => 27,
        ItemType::WoodenAxe => 28,
        ItemType::StoneAxe => 29,
        ItemType::IronAxe => 30,
        ItemType::DiamondAxe => 31,
        ItemType::WoodenShovel => 32,
        ItemType::StoneShovel => 33,
        ItemType::IronShovel => 34,
        ItemType::DiamondShovel => 35,
        ItemType::WoodenHoe => 36,
        ItemType::StoneHoe => 37,
        ItemType::IronHoe => 38,
        ItemType::DiamondHoe => 39,
        _ => 255,
    }
}

pub fn item_from_u8(v: u8) -> Option<ItemType> {
    match v {
        0 => Some(ItemType::Block(BlockType::Grass)),
        1 => Some(ItemType::Block(BlockType::Dirt)),
        2 => Some(ItemType::Block(BlockType::Wood)),
        3 => Some(ItemType::Block(BlockType::Stone)),
        4 => Some(ItemType::Apple),
        5 => Some(ItemType::Bread),
        6 => Some(ItemType::Bucket),
        7 => Some(ItemType::WaterBucket),
        8 => Some(ItemType::DiamondSword),
        9 => Some(ItemType::DiamondPickaxe),
        10 => Some(ItemType::Porkchop),
        11 => Some(ItemType::CookedPorkchop),
        12 => Some(ItemType::Beef),
        13 => Some(ItemType::CookedBeef),
        14 => Some(ItemType::Mutton),
        15 => Some(ItemType::CookedMutton),
        16 => Some(ItemType::WhiteWool),
        17 => Some(ItemType::Leather),
        18 => Some(ItemType::Stick),
        19 => Some(ItemType::Coal),
        20 => Some(ItemType::IronIngot),
        21 => Some(ItemType::WoodenPickaxe),
        22 => Some(ItemType::StonePickaxe),
        23 => Some(ItemType::IronPickaxe),
        24 => Some(ItemType::WoodenSword),
        25 => Some(ItemType::StoneSword),
        26 => Some(ItemType::IronSword),
        27 => Some(ItemType::Diamond),
        28 => Some(ItemType::WoodenAxe),
        29 => Some(ItemType::StoneAxe),
        30 => Some(ItemType::IronAxe),
        31 => Some(ItemType::DiamondAxe),
        32 => Some(ItemType::WoodenShovel),
        33 => Some(ItemType::StoneShovel),
        34 => Some(ItemType::IronShovel),
        35 => Some(ItemType::DiamondShovel),
        36 => Some(ItemType::WoodenHoe),
        37 => Some(ItemType::StoneHoe),
        38 => Some(ItemType::IronHoe),
        39 => Some(ItemType::DiamondHoe),
        _ => None,
    }
}
