use super::item_type::ItemType;

pub fn item_name(item: &ItemType) -> &'static str {
    match item {
        ItemType::Block(b) => b.name(),
        ItemType::Apple => "Apple",
        ItemType::Bread => "Bread",
        ItemType::Porkchop => "Raw Porkchop",
        ItemType::CookedPorkchop => "Cooked Porkchop",
        ItemType::Beef => "Raw Beef",
        ItemType::CookedBeef => "Steak",
        ItemType::Mutton => "Raw Mutton",
        ItemType::CookedMutton => "Cooked Mutton",
        ItemType::WhiteWool => "White Wool",
        ItemType::Leather => "Leather",
        ItemType::Stick => "Stick",
        ItemType::Coal => "Coal",
        ItemType::IronIngot => "Iron Ingot",
        ItemType::Diamond => "Diamond",
        ItemType::WoodenPickaxe => "Wooden Pickaxe",
        ItemType::StonePickaxe => "Stone Pickaxe",
        ItemType::IronPickaxe => "Iron Pickaxe",
        ItemType::DiamondPickaxe => "Diamond Pickaxe",
        ItemType::WoodenSword => "Wooden Sword",
        ItemType::StoneSword => "Stone Sword",
        ItemType::IronSword => "Iron Sword",
        ItemType::DiamondSword => "Diamond Sword",
        ItemType::WoodenAxe => "Wooden Axe",
        ItemType::StoneAxe => "Stone Axe",
        ItemType::IronAxe => "Iron Axe",
        ItemType::DiamondAxe => "Diamond Axe",
        ItemType::WoodenShovel => "Wooden Shovel",
        ItemType::StoneShovel => "Stone Shovel",
        ItemType::IronShovel => "Iron Shovel",
        ItemType::DiamondShovel => "Diamond Shovel",
        ItemType::WoodenHoe => "Wooden Hoe",
        ItemType::StoneHoe => "Stone Hoe",
        ItemType::IronHoe => "Iron Hoe",
        ItemType::DiamondHoe => "Diamond Hoe",
        ItemType::Bucket => "Bucket",
        ItemType::WaterBucket => "Water Bucket",
    }
}
